// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://eagmdsugaflbowqaihiq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZ21kc3VnYWZsYm93cWFpaGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5OTgyNDYsImV4cCI6MjA0ODU3NDI0Nn0.0A1mMIVSlwRXDi3kkHjk-ljp1F0pXvmCIy6hM0Ezxh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);